"""initial schema

Revision ID: 0001_schema_inicial
Revises:
Create Date: 2026-08-21 18:47:14.861604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_schema_inicial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sport',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('channel',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('dark_color', sa.String(length=32), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('dark_image', sa.Text(), nullable=True),
    sa.Column('selected_image', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('catalog_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_code'], ['source.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'name', name='uq_channel_source_name')
    )
    op.create_table('competition',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('dark_image', sa.Text(), nullable=True),
    sa.Column('selected_image', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('catalog_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_code'], ['source.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'name', name='uq_competition_source_name')
    )
    op.create_table('team',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('normalized_name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_code'], ['source.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'normalized_name', name='uq_team_source_normalized_name')
    )
    op.create_table('catalog_meta',
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_code'], ['source.code'], ),
    sa.PrimaryKeyConstraint('source_code', 'key')
    )
    op.create_table('scrape_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('job_type', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_code'], ['source.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('sport_code', sa.String(length=16), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('time_raw', sa.String(length=8), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('competition_text', sa.String(length=128), nullable=False),
    sa.Column('competition_id', sa.BigInteger(), nullable=True),
    sa.Column('round', sa.String(length=64), nullable=False),
    sa.Column('home_text', sa.String(length=128), nullable=False),
    sa.Column('home_team_id', sa.BigInteger(), nullable=True),
    sa.Column('away_text', sa.String(length=128), nullable=False),
    sa.Column('away_team_id', sa.BigInteger(), nullable=True),
    sa.Column('broadcast_raw', sa.Text(), nullable=False),
    sa.Column('has_broadcast', sa.Boolean(), sa.Computed("broadcast_raw <> ''", persisted=True), nullable=False),
    sa.Column('source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['source_code'], ['source.code'], ),
    sa.ForeignKeyConstraint(['sport_code'], ['sport.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'sport_code', 'game_date', 'time_raw', 'home_text', 'away_text', name='uq_game_natural_key')
    )
    op.create_index('ix_game_away_team_id', 'game', ['away_team_id'], unique=False)
    op.create_index('ix_game_competition_id', 'game', ['competition_id'], unique=False)
    op.create_index('ix_game_date_sport', 'game', ['game_date', 'sport_code'], unique=False)
    op.create_index('ix_game_home_team_id', 'game', ['home_team_id'], unique=False)
    op.create_index('ix_game_source', 'game', ['source_code'], unique=False)
    op.create_table('game_broadcast',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('raw_token', sa.Text(), nullable=False),
    sa.Column('platform_text', sa.Text(), nullable=False),
    sa.Column('qualifier_text', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('match_method', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'position', name='uq_game_broadcast_position')
    )
    op.create_index('ix_game_broadcast_channel_id', 'game_broadcast', ['channel_id'], unique=False)
    # ### end Alembic commands ###

    # Seed: the canonical sport vocabulary shared across sources (ADR 0003) —
    # small and closed, it does not change at runtime. `source` is NOT seeded
    # here: it is derived from the registry in app/core/registry.py on every
    # startup (ADR 0001), not hand-typed into a migration.
    sport_table = sa.table(
        "sport",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
    )
    op.bulk_insert(
        sport_table,
        [
            {"code": "futebol", "name": "Futebol"},
            {"code": "basquete", "name": "Basquete"},
            {"code": "volei", "name": "Vôlei"},
            {"code": "nfl", "name": "NFL"},
            {"code": "nhl", "name": "NHL"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_broadcast_channel_id', table_name='game_broadcast')
    op.drop_table('game_broadcast')
    op.drop_index('ix_game_source', table_name='game')
    op.drop_index('ix_game_home_team_id', table_name='game')
    op.drop_index('ix_game_date_sport', table_name='game')
    op.drop_index('ix_game_competition_id', table_name='game')
    op.drop_index('ix_game_away_team_id', table_name='game')
    op.drop_table('game')
    op.drop_table('scrape_run')
    op.drop_table('catalog_meta')
    op.drop_table('team')
    op.drop_table('competition')
    op.drop_table('channel')
    op.drop_table('sport')
    op.drop_table('source')
    # ### end Alembic commands ###
